website:
  # The website base URL.
  url: 'http://localhost'
  # Port the website runs on
  port: 9001

  # Whether the website is behind a proxy (e.g. Nginx)
  proxy: false

database:
  # Driver to use, supports 'h2', 'sqlite' and 'postgres'
  driver: h2

  # Host and port, unused for sqlite
  host: localhost
  port: 5432

  # Name of the database
  # For sqlite, this is the path to the database file
  # For postgres, this is the name of the database
  database: wiki_site

  # DB credentials, unused for sqlite
  username: wiki_user
  password: wiki_password
